SELECT '/home/grep/src/' || BOARD_ID || '/' || FILE_ID || FILE_NAME || FILE_EXT  AS FILE_PATH
FROM (SELECT B.BOARD_ID, B.FILE_ID, B.FILE_NAME, B.FILE_EXT, A.VIEWS
      FROM USED_GOODS_BOARD A JOIN USED_GOODS_FILE B 
      ON A.BOARD_ID = B.BOARD_ID
      WHERE (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD) = A.VIEWS
     )
ORDER BY FILE_ID desc